// packages/vue-zephyr/src/components-local/Group.tsx
import { defineComponent } from "vue";
import { tw } from "twind";

export const Group = defineComponent({
  setup(_, { slots }) {
    return () => <div class={tw`space-y-8`}>{slots.default?.() ?? null}</div>;
  },
});

export const Subgroup = defineComponent({
  setup(_, { slots }) {
    return () => <div class={tw`space-y-4`}>{slots.default?.() ?? null}</div>;
  },
});

// packages/react-zephyr/src/components-local/Group.tsx
import { ReactElement } from "react";
import "@twind/macro";

interface Props {
  children: ReactElement;
}

export const Group = ({ children }: Props): ReactElement => {
  return <div tw="space-y-8">{children}</div>;
};

export const Subgroup = ({ children }: Props): ReactElement => {
  return <div tw="space-y-4">{children}</div>;
};
