// packages/vue-zephyr/src/components-local/MainNav.vue
<template>
  <nav :class="tw`flex items-center`">
    <Link to="/" :class="tw`text-lg flex items-center`">
      <inline-svg
        :class="tw`w-6 mr-3`"
        :src="require('@public/simple-logo.svg')"
      />
      <div>Vue Zephyr</div>
    </Link>
    <ul :class="tw`flex items-center space-x-4 ml-auto`">
      <li>
        <Link to="/docs/install">Documentation</Link>
      </li>
      <li>
        <Link to="/guides">Guides</Link>
      </li>
      <li>
        <Anchor href="https://twitter.com/usezephyr" newTab>Updates</Anchor>
      </li>
      <li>|</li>
      <li>
        <LightSwitch />
      </li>
    </ul>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { tw } from "twind";
import InlineSvg from "vue-inline-svg";
import Link from "@components-local/Link.vue";
import LightSwitch from "@components-local/LightSwitch.vue";
import Anchor from "@components/Anchor/Anchor.vue";
export default defineComponent({
  components: {
    InlineSvg,
    Link,
    LightSwitch,
    Anchor,
  },
  setup() {
    return { tw };
  },
});
</script>

// packages/react-zephyr/src/components-local/MainNav.tsx
import { ReactElement } from "react";
import "@twind/macro";
import Link from "next/link";
import Logo from "@public/simple-logo.svg";
import useDarkMode from "@/src/utils/darkMode";

interface Props {}

export default function MainNav({}: Props): ReactElement {
  const { darkMode, setDarkMode } = useDarkMode();
  return (
    <nav tw="flex items-center">
      <Link href="/">
        <a tw="text-lg flex items-center">
          <Logo tw="w-6 mr-3" />
          <div>React Zephyr</div>
        </a>
      </Link>
      <ul tw="flex items-center space-x-4 ml-auto">
        <li>
          <Link href="/docs/install">Documentation</Link>
        </li>
        <li>
          <Link href="/guides">Guides</Link>
        </li>
        <li>
          <Link href="https://twitter.com/usezephyr">Updates</Link>
        </li>
        <li>|</li>
        <li>
          <button onClick={() => setDarkMode(!darkMode)}>
            {darkMode ? "Dark" : "Light"}
          </button>
        </li>
      </ul>
    </nav>
  );
}
