// packages/vue-zephyr/src/components/Button/Button.vue
<template>
  <button :class="classes">
    <slot name="default"></slot>
  </button>
</template>

<script lang="ts">
import { defineComponent, computed, inject } from "vue";
import { variant, classRemove, classAppend, status, size } from "@/props";
import { Classy } from "@/utils/helpers.ts";
import Theme from "./theme";

export default defineComponent({
  name: "Button",
  props: {
    ...classAppend(),
    ...classRemove(),
    ...variant({
      default: "primary",
    }),
    ...status({
      default: "default",
      validator: (v) => ["loading", "default"].includes(v),
    }),
    ...size({
      default: "md",
      validator: (v) => ["xs", "sm", "md", "lg", "xl"].includes(v),
    }),
  },
  setup(props) {
    const { value: theme } = computed(() => Theme(inject("userTheme", {})));
    const classes = computed(() =>
      new Classy("italic")
        .append(theme[props.variant])
        .append(theme.size[props.size])
        .append(props.classAppend)
        .remove(props.classRemove)
        .twind(inject("twindEnable", true))
        .val()
    );
    return { classes };
  },
});
</script>

// packages/react-zephyr/src/components/Button/Button.tsx
import { ReactElement, ReactNode, useContext } from "react";
import { Classy } from "@utils/helpers";
import Theme from "./Button.theme";
import { ZephyrContext } from "@utils/context";

export default function Button({
  children = null as ReactNode,
  classAppend = "" as Classes,
  classRemove = "" as Classes,
  variant = "primary" as Variant,
  size = "md" as string,
  status = null as string | null,
}): ReactElement {
  const theme = Theme(useContext(ZephyrContext));
  const classes = new Classy()
    .append(theme[status ?? variant])
    .append(theme.size[size])
    .append(classAppend)
    .remove(classRemove)
    .twind()
    .val();

  return <button className={classes}>{children}</button>;
}
