// packages/react-zephyr/src/components-local/CodeBlock.tsx
import { ReactElement, useEffect } from "react";
import clsx from "clsx";
import { tw } from "twind";
import Strip from "strip-indent";
import PrismJs from "prismjs";
import "prismjs/components/prism-json";
import "prismjs/components/prism-bash";
import "prismjs/plugins/line-numbers/prism-line-numbers.js";
import "prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.js";

interface Props {
  code: string;
  lang: "js" | "vue" | "json" | "html" | "bash";
  inline?: boolean;
}

export default function CodeBlock({
  code,
  lang = "js",
  inline = false,
}: Props): ReactElement {
  useEffect(() => {
    PrismJs.highlightAll();
  }, []);

  return (
    <div
      className={clsx([
        tw`bg-gray-100 dark:bg-gray-800 overflow-auto`,
        !inline ? tw`line-numbers px-1 py-2` : tw`px-8 py-6`,
      ])}
    >
      <code className={`language-${lang}`}>{Strip(code)}</code>
    </div>
  );
}

// packages/vue-zephyr/src/components-local/CodeBlock.vue
<template>
  <div
    :class="[
      tw`bg-gray-100 dark:bg-gray-800 overflow-auto`,
      !inline ? tw`line-numbers px-1 py-2` : tw`px-8 py-6`
    ]"
  >
    <Prism :language="lang === 'vue' ? 'html' : lang" :inline="inline">{{
      formattedCode
    }}</Prism>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, onMounted } from "vue";
import { tw } from "twind";
import Strip from "strip-indent";
import PrismJs from "prismjs";
import "prismjs/components/prism-json";
import "prismjs/components/prism-bash";
import "prismjs/plugins/line-numbers/prism-line-numbers.js";
import "prismjs/plugins/normalize-whitespace/prism-normalize-whitespace.js";
import Prism from "vue-prism-component";

export default defineComponent({
  components: {
    Prism,
  },
  props: {
    code: {
      type: String,
      required: true,
    },
    lang: {
      type: String,
      default: "html",
      validator: (v: string) =>
        ["js", "vue", "json", "html", "bash"].includes(v),
    },
    inline: {
      type: Boolean,
      default: false,
    },
  },
  setup(props) {
    const formattedCode = computed(() => Strip(props.code));
    onMounted(() => {
      PrismJs.highlightAll();
    });
    return { formattedCode, tw };
  },
});
</script>
