// packages/react-zephyr/src/components-local/Example.tsx
import { ReactElement, ReactNode } from "react";
import CodeBlock from "@components-local/CodeBlock";
import { tw } from "twind";

interface Props {
  children: ReactNode;
  code: string;
  lang?: "js" | "vue" | "json" | "html" | "bash";
  inline?: boolean;
}

export default function Example({
  children,
  code,
  lang,
  inline,
}: Props): ReactElement {
  return (
    <div>
      <div
        className={tw`p-8 border(t-2 r-2 l-2 gray-100 dark:gray-800) bg-white dark:bg-gray-700 dark:bg-opacity-60 rounded-t-lg`}
      >
        {children}
      </div>
      <div className={tw`rounded-b-lg overflow-hidden`}>
        <CodeBlock lang={lang} code={code} inline={inline} />
      </div>
    </div>
  );
}

// packages/vue-zephyr/src/components-local/Example.vue
<template>
  <div>
    <div :class="classes.slot">
      <slot></slot>
    </div>
    <div :class="classes.code">
      <CodeBlock :lang="lang" :code="code" />
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from "vue";
import { tw } from "twind";
import CodeBlock from "@components-local/CodeBlock.vue";

export default defineComponent({
  components: {
    CodeBlock,
  },
  props: {
    code: {
      type: String,
      required: true,
    },
    lang: {
      type: String,
      default: "html",
      validator: (v: string) => ["js", "vue", "json", "html"].includes(v),
    },
  },
  setup() {
    const classes = computed(() => {
      return {
        slot: tw`p-8 border(t-2 r-2 l-2 gray-100 dark:gray-800) bg-white dark:bg-gray-700 dark:bg-opacity-60 rounded-t-lg`,
        code: tw`rounded-b-lg overflow-hidden`,
      };
    });
    return { tw, classes };
  },
});
</script>
