// packages/react-zephyr/src/components-local/Heading.tsx
import { ReactElement, ReactNode } from "react";
import "@twind/macro";

interface Props {
  children: ReactNode;
}

export const H3 = ({ children }: Props): ReactElement => {
  return (
    <h3 tw="font-medium text-gray-900 dark:text-gray-100 text-3xl">
      {children}
    </h3>
  );
};

export const H4 = ({ children }: Props): ReactElement => {
  return (
    <h4 tw="font-medium text-gray-900 dark:text-gray-100 text-xl">
      {children}
    </h4>
  );
};

// packages/vue-zephyr/src/components-local/Heading.tsx
import { defineComponent } from "vue";
import { tw } from "twind";

export const H3 = defineComponent({
  setup(_, { slots }) {
    return () => (
      <h3 class={tw`font-medium text-gray-900 dark:text-gray-100 text-3xl`}>
        {slots.default?.() ?? null}
      </h3>
    );
  },
});

export const H4 = defineComponent({
  setup(_, { slots }) {
    return () => (
      <h4 class={tw`font-medium text-gray-900 dark:text-gray-100 text-xl`}>
        {slots.default?.() ?? null}
      </h4>
    );
  },
});
