// packages/react-zephyr/src/layouts/Default.tsx
import { ReactElement, ReactNode, useEffect } from "react";
import "@twind/macro";
import Head from "@components-local/Head";
import Container from "@components-local/Container";
import MainNav from "@components-local/MainNav";
import Sidebar from "@components-local/Sidebar";
import useDarkMode from "@utils/darkMode";
import { heightClasses, darkModeClasses } from "@utils/documentClasses";

interface Props {
  children: ReactNode;
  title: String;
}

export default function DefaultLayout({
  children,
  title,
}: Props): ReactElement {
  const { darkMode } = useDarkMode();

  // Apply document classes
  useEffect(() => {
    darkModeClasses();
    heightClasses();
  }, []);

  return (
    <div tw="h-full flex flex-col">
      <Head>
        <title>{title} | React Zephyr</title>
      </Head>

      <header>
        <div tw="bg-blue-600 text-white">
          <Container>
            <div tw="py-6">
              <MainNav />
            </div>
          </Container>
        </div>
      </header>

      <main tw="lg:mt-8">
        <Container>
          <div tw="lg:grid grid-cols-4 gap-12 mt-12">
            <div tw="col-span-1 lg:mt-1.5">
              <Sidebar active={title} />
            </div>
            <div tw="col-span-3 mt-8 lg:mt-0">{children}</div>
          </div>
        </Container>
      </main>

      <footer tw="mt-auto">This be the footer</footer>
    </div>
  );
}

// packages/vue-zephyr/src/layouts/default.vue
<template>
  <main :class="tw`h-full flex(& col) relative`">
    <div :class="tw`bg-green-600 text-white py-6`">
      <Container>
        <MainNav />
      </Container>
    </div>
    <div :class="tw`lg:mt-8 layout`">
      <Container>
        <div :class="tw`lg:grid grid-cols-4 gap-12 mt-12`">
          <div :class="tw`col-span-1 lg:mt-1.5`">
            <Sidebar />
          </div>
          <div :class="tw`col-span-3 mt-8 lg:mt-0`">
            <BaseLayout />
          </div>
        </div>
      </Container>
    </div>
    <Footer :class="tw`mt-auto`" />
  </main>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { tw } from "twind";
import { isDark } from "@utils/darkMode";
import BaseLayout from "@layouts/_base.vue";
import MainNav from "@components-local/MainNav.vue";
import Footer from "@components-local/Footer.vue";
import Container from "@components-local/Container.vue";
import Sidebar from "@components-local/Sidebar.vue";

export default defineComponent({
  components: {
    BaseLayout,
    MainNav,
    Footer,
    Container,
    Sidebar,
  },
  setup() {
    return { tw, isDark };
  },
});
</script>
